#!/usr/bin/env python3

import numpy as np
from argparse import ArgumentParser
from os import sys
from tomso import adipls

parser = ArgumentParser()
parser.add_argument('agsm', type=str,
                    help="ADIPLS grand summary (AGSM) from which to read data")
args = parser.parse_args()

css = adipls.load_agsm(args.agsm, return_object=True)
np.savetxt(sys.stdout, np.vstack([css.l, css.n, css.nu*1e6, css.E]).T,
           fmt='%4i%4i%16.7f%16.7e')
