#!/usr/bin/env python3

import numpy as np
from argparse import ArgumentParser
from os import sys
from tomso import adipls

parser = ArgumentParser()
parser.add_argument('agsm', type=str,
                    help="ADIPLS grand summary (AGSM) from which to read data")
args = parser.parse_args()

css = adipls.load_agsm(args.agsm)
freq = np.sqrt(css['sigma2_c']/css['sigma2'])*1e5/6/css['Pi_E']
np.savetxt(sys.stdout, np.vstack([css['ell'], css['enn'], freq, css['E']]).T,
           fmt='%4i%4i%16.7f%16.7e')
