#!/usr/bin/env python3

import numpy as np
from argparse import ArgumentParser

parser = ArgumentParser("""Convert a CSV file to a NumPy binary.""")
parser.add_argument('csv', type=str, help="filename of input CSV file")
parser.add_argument('npy', type=str, help="filename of output NumPy binary file")
args = parser.parse_args()

np.save(args.npy, np.genfromtxt(args.csv, delimiter=',', names=True))
