#!/usr/bin/env python3

import numpy as np
import AADG3
from collections import OrderedDict
from argparse import ArgumentParser

def logW_meta(nu, numax, Teff, a_alpha, b_alpha, c_alpha,
              a_Walpha, b_Walpha, c_Walpha,
              a_DWdip, b_DWdip, c_DWdip,
              a_nudip, b_nudip, c_nudip,
              a_Wdip, b_Wdip, c_Wdip):
    alpha = a_alpha + b_alpha*Teff + c_alpha*numax
    Walpha = a_Walpha + b_Walpha*Teff + c_Walpha*numax
    DWdip = a_DWdip + b_DWdip*Teff + c_DWdip*numax
    nudip = a_nudip + b_nudip*Teff + c_nudip*numax
    Wdip = a_Wdip + b_Wdip*Teff + c_Wdip*numax

    output = alpha*np.log(nu/numax) + np.log(Walpha)
    output[DWdip < 1.0] += (np.log(DWdip)/(1. + (2*np.log(nu/nudip)/np.log(Wdip))**2))[DWdip < 1.0]
    return output

parser = ArgumentParser()
parser.add_argument('gyre_filename', type=str,
                    help="filename of input GYRE summary")
parser.add_argument('basename', type=str,
                    help="base filename for AADG3 inputs")
parser.add_argument('--cadence', type=float, default=120.0,
                    help="cadence, in s (default=120.0)")
parser.add_argument('-v', type=float, default=0.0,
                    help="radial velocity, in km/s (default=0.0)")
# parser.add_argument('-v', '--verbose', action='store_true')
parser.add_argument('--splitting', type=float, default=-1,
                    help="constant rotation splitting, ignored if < 0, "
                    "in which case rotation is taken from summary "
                    "if available, otherwise rotation = 0 (default -1)")
parser.add_argument('--inclination', type=float, default=-1,
                    help="inclination, ignored if < 0, "
                    "in which case a random inclination is generated "
                    "(default -1)")
parser.add_argument('--min-H', type=float, default=-1,
                    help="minimum for height H (default=-1, i.e. keep all modes)")
args = parser.parse_args()

with open(args.gyre_filename, 'r') as f:
    lines = f.readlines()

header = np.genfromtxt(lines[2:4], names=True, dtype=None,
                       encoding='utf-8')
summary = np.genfromtxt(lines[5:], names=True, dtype=None,
                        encoding='utf-8')

Lsun = 3.8418e33
Rsun = 6.9598e10
Msun = 1.9892e33
boltz = 5.6704e-5
Teff_sun = (Lsun/(4.*np.pi*boltz*Rsun**2))**0.25
numax_sun = 3090.0
Dnu_sun = 135.1
sig_sun = 60.0
warmup = np.random.randint(2**16, size=100)
c = 299792.458

M = header['M_star']/Msun  # 1.0  # Msun
R = header['R_star']/Rsun  # 1.0  # Rsun
L = header['L_star']/Lsun  # 1.0  # Lsun
Teff = (L/R**2)**0.25*Teff_sun
numax = numax_sun*(M/R**2/(Teff/Teff_sun)**0.5)
Dnu = Dnu_sun*np.sqrt(M/R**3)
sig = np.sqrt(L**2/M**3/(Teff/Teff_sun)**5.5*(numax/numax_sun))*sig_sun

modes_filename = args.basename + '.con'
rotation_filename = args.basename + '.rot'

namelist = OrderedDict()
namelist['user_seed'] = np.random.randint(100, 2**28-1)
namelist['cadence'] = 120.0
vis = np.array([1.0, 1.505, 0.62, 0.075])  # medians from Lund et al. (2017)
namelist['n_relax'] = 6*720
namelist['n_fine'] = 50
namelist['sig'] = sig
namelist['rho'] = 0.45
namelist['tau'] = 250.0/(numax/3090.)

if args.inclination >= 0:
    namelist['inclination'] = args.inclination
else:
    namelist['inclination'] = np.degrees(np.arccos(np.random.rand()))

for i in range(1, 4):
    namelist['p(%i)' % i] = vis[i]
    
namelist['add_granulation'] = True
namelist['modes_filename'] = modes_filename
namelist['rotation_filename'] = rotation_filename
namelist['output_filename'] = args.basename + '.asc'

AADG3.save_namelist(args.basename + '.in', namelist)

l = summary['l'].astype(int)
n = summary['n_pg'].astype(int)
nu = summary['Refreq']
E = summary['E_norm']

# all As are A_rms
# 
Amax_sun = 2.1        # ppm
Tred_sun = 8907.0
dT = 1250.0
    
Tred = Tred_sun*L**-0.093
beta = 1.0 - np.exp((Teff-Tred)/dT)
Amax = Amax_sun*beta*L/M*(Teff/Teff_sun)**-2
Henv = Amax**2/Dnu
wenv = 0.66*numax**0.88
if Teff > Teff_sun:
    wenv *= 1.0 + 6e-4*(Teff-Teff_sun)
    
cenv = wenv/2./np.sqrt(2.*np.log(2.))  # FWHM -> sigma

Q = E/np.interp(nu, nu[l==0], E[l==0])

# width = scaling.lund_width(nu, numax)/Q
# using 25 of Guy's red giants
p25 = [-3.71033159e+00,  1.07268220e-03,  1.88285544e-04, -7.20902433e+01,
        1.54336225e-02,  9.10050555e-04, -2.26620472e-01,  5.08279583e-05,
        2.71537654e-06, -2.18970560e+03,  4.30163078e-01,  8.42663954e-01,
       -5.63927133e-01,  1.13801669e-04,  1.31215914e-04]
width = np.exp(logW_meta(nu, numax, Teff, *p25))/Q

H = Henv*np.exp(-(nu-numax)**2/2./cenv**2)/Q
power = H*Dnu
height = 2./np.pi*power/width*vis[l]
bkg = 4.*namelist['sig']**2*namelist['tau']/(1.0+(1e-6*nu*namelist['tau']*2.*np.pi)**2)/2e6
I = height/bkg > args.min_H

nu = nu*np.sqrt((1-args.v/c)/(1+args.v/c))

np.savetxt(modes_filename, 
           np.vstack([l, n, nu, width, power, 0.0*nu]).T[I],
           fmt=['%2i','  %5i','  %12.7e','  %12.7e','  %12.7e','  %12.8e'])

if args.splitting >= 0:
    dnu_rot = args.splitting*np.ones_like(nu)
else:
    try:
        dnu_rot = summary['dfreq_rot']
    except ValueError:
        dnu_rot = np.zeros_like(nu)

with open(rotation_filename, 'w') as f:
    for ni, li, dnu_roti in zip(n[I], l[I], dnu_rot[I]):
        for m in range(1, li+1):
            f.write('%5i%3i%3i%12.7f\n' % (ni, li, m, dnu_roti))

